# Backward-compatibility shim — canonical source is src.core.graph + src.nodes
# Remove once Story 7.6 updates all test imports to src.*
from src.core.graph import (  # noqa: F401
    CONDITIONAL_EDGE_LABELS,
    LINEAR_EDGE_LABELS,
    LINEAR_ROUTE_TARGETS,
    NODE_HANDLERS,
    PIPELINE_NODE_METADATA,
    PIPELINE_NODE_ORDER,
    PIPELINE_STAGE_TO_NODE,
    ROUTE_HANDLERS,
    _append_taken_edge,
    _make_instrumented_node,
    _make_recording_router,
    _resolve_route_target,
    _route_after_ingest,
    _route_after_parse,
    _route_gaps,
    _route_results,
    _route_spec_review,
    _route_test_plan,
    build_pipeline,
    record_route_transition,
    reset_visualization_trace,
    run_pipeline_node,
)
from src.nodes import (  # noqa: F401
    analyze_results,
    detect_gaps,
    execute_tests,
    fill_gaps,
    generate_tests,
    ingest_spec,
    parse_spec,
    review_results,
    review_spec,
    review_test_plan,
)
from src.nodes.fill_gaps import (  # noqa: F401
    _apply_gap_answer,
    _apply_global_auth_if_unambiguous,
    _auth_state_from_answer,
    _find_endpoint,
    _is_actionable_answer,
    _is_conversational_mode,
)
